### PR TITLE
fix build with gcc-15.0.1 too many arguments to function error

### PR DESCRIPTION
**Pull request by markyang92**
* GCC 15 considers it an error to pass arguments to a function pointer defined to take no arguments. This results in a 'too many arguments to function' error.

  At the problematic function pointer call sites, the pointer is cast to a variadic function pointer type (SQLRETURN (*)(...)) to avoid the error.

* see more details in http://errors.yoctoproject.org/Errors/Details/850317 ../../libiodbc-3.52.16/iodbc/hdbc.c: In function '_iodbcdm_SetConnectOption': ../../libiodbc-3.52.16/iodbc/hdbc.c:567:49: error: too many arguments to function 'hproc3'; expected 0, have 4
  567 |               CALL_DRIVER (hdbc, pdbc, retcode, hproc3,
      |                                                 ^~~~~~
  568 |                   (pdbc->dhdbc, fOption, vParam, 0));
      |                    ~~~~~~~~~~~
../../libiodbc-3.52.16/iodbc/itrace.h:113:15: note: in definition of macro 'CALL_DRIVER'
  113 |         ret = proc plist; \
      |               ^~~~
../../libiodbc-3.52.16/iodbc/hdbc.c:583:49: error: too many arguments to function 'hproc3'; expected 0, have 4
  583 |               CALL_DRIVER (hdbc, pdbc, retcode, hproc3,
      |                                                 ^~~~~~
  584 |                   (pdbc->dhdbc, fOption, vParam, SQL_NTS));
      |                    ~~~~~~~~~~~
../../libiodbc-3.52.16/iodbc/itrace.h:113:15: note: in definition of macro 'CALL_DRIVER'
  113 |         ret = proc plist; \
      |               ^~~~
../../libiodbc-3.52.16/iodbc/hdbc.c:597:45: error: too many arguments to function 'hproc2'; expected 0, have 3
  597 |           CALL_DRIVER (hdbc, pdbc, retcode, hproc2,
      |                                             ^~~~~~
  598 |               (pdbc->dhdbc, fOption, vParam));
      |                ~~~~~~~~~~~
....

../../libiodbc-3.52.16/iodbc/connect.c:2970:19: error: too many arguments to function 'dialproc'; expected 0, have 6
 2970 |         retcode = dialproc (hwnd,       /* window or display handle */
      |                   ^~~~~~~~  ~~~~

### CODE REVIEW

**Comment by markyang92** [comment]
Build failure in Clang.

**Comment by pkleef** [comment]
I was able to recreate using a beta of the Fedora Core 42 distribution.

This appears to be an issue with a beta version of GCC 15.01 that has not yet been officially been released.

The construction that you proposed cannot be used by many current compilers which are used by  current distributions, using the default compiler flags normally used on these platforms.

I have to think of another way to make this work without having to use another level of `ifdefs`.

As a workaround i suggest you add the `--std=gnu17` flag to your CFLAGS so you can build iODBC on your platform. 


## Examples

### macox Sequoia (15.4) - Apple clang version 17.0.0 (clang-1700.0.13.3)
```
../../iodbc/connect.c:2970:35: error: ISO C requires a named parameter before '...'
 2970 |         retcode = ((SQLRETURN (*)(...)) dialproc) (hwnd,       /* window or display handle */
      |
```

### Ubuntu 24.04 - clang version 18.1.3:
```
  ../../iodbc/connect.c:2970:35: error: ISO C requires a named parameter before '...'
 2970 |         retcode = ((SQLRETURN (*)(...)) dialproc) (hwnd,        /* window or display handle */
      |                                   ^
```

### RedHat 9 - gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-5)
```
../../iodbc/connect.c: In function ‘SQLDriverConnect_Internal’:
../../iodbc/connect.c:2970:35: error: ISO C requires a named argument before ‘...’
 2970 |         retcode = ((SQLRETURN (*)(...)) dialproc) (hwnd,       /* window or display handle */
      |
```
